### PR TITLE
CORE-8752 Allow users to delete Collaborator Lists

### PR DESCRIPTION
**Pull request by ash3rz**
These are the changes for deleting a Collaborator List (group).

### CODE REVIEW

**Comment by tedgin** [comment]
The logic looks tight.  But since we talked about documenting in chat and everyone seemed to like the idea, do you mind documenting the newly created interface methods? :D

**Comment by ash3rz** [comment]
I think it's a good idea to start the habit now - sure, will do!  And thanks for the review!

**Comment by tedgin** [comment]
LGTM :shipit:

**Comment by ash3rz** [comment]
Thanks for the review!

**Pull request merged**
