### PR TITLE
CORE-8888 Set maxInactiveInterval on the user's session to configure …

### PR DESCRIPTION
**Pull request by ash3rz**
…timeout length

NOTE: Requires ansible changes before merging.

### CODE REVIEW

**Comment by ash3rz** [comment]
😄  Thanks for the review!  I'll merge in the ansible/consul changes and then merge this in.

**Comment by ash3rz** [comment]
Oh, before I do that I was assuming 60 minutes for the timeout was appropriate - I thought there was some other auth restriction set to 60 minutes (could be remembering wrong).  Does that make sense or should we use a different time?

**Comment by psarando** [comment]
If our CAS timeout is 8 hours, maybe this Spring session timeout should match?

**Comment by ash3rz** [comment]
Sounds good to me!  I'll make sure that's reflected in the ansible change then.

**Pull request merged**
