### PR TITLE
CORE-8642 Add link to WashU genome browser in `Send to Genome Browser…

### PR DESCRIPTION
**Pull request by sri2k1us**
…` dialog.

### CODE REVIEW

**Comment by sri2k1us** [comment]
Merging directly since this change affect property files only.

**Comment by cyverse-org** [comment]
Does this include the additional file types that are to be allowed for byte
range access via http ?

On Tue, Mar 21, 2017 at 9:46 AM, Sriram Srinivasan <notifications@github.com

**Comment by sri2k1us** [comment]
Nope. Just the link to WashU browser. File types detection done as a separate issue by Ian.

**Comment by cyverse-org** [comment]
Thanks ..as long as we can push that out relatively soon or together it
will be good.

**Comment by sri2k1us** [comment]
Can you please answer Ian's questions here - https://pods.iplantcollaborative.org/jira/browse/CORE-8626

**Comment by cyverse-org** [comment]
Please ask the Washu person for example and how to test it with their
browser for tabix indexed file  I am not sure myself as I have not used it.

Ian seems to be on target with his comment about vcf

**Pull request merged**
